# 应用名称
spring:
  application:
    name: quartz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://rm-2zewws6e31p267bksro.mysql.rds.aliyuncs.com:3306/quartz?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: zhaohe1
    password: Zz112211
# 应用服务 WEB 访问端口
server:
  port: 8080
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zh.quartz.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/quartz/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql